version: 2
jobs:
 build:
  docker:
   - image: holochain/holonix
  steps:
   - checkout
   - run:
      name: start dynamodb
      background: true
      command: nix-shell --run dynamodb

   - run:
      name: wait for dynamodb
      command: nix-shell --run 'aws dynamodb list-tables --endpoint-url=http://localhost:8000'

workflows:
 version: 2
 build:
  jobs:
   - build
